<a href="https://colab.research.google.com/github/Niharika-20-MAI-01/Winter-2021-Deep-Learning-LabCSE6037-Niharika-20MAI01/blob/main/20MAI0001_DL_single_layer_Perceptron_Prob_1_Asgn_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DL-Lab-CSE6037_Lab-Assignment-1_Problem-1_SLP

Submitted By: 20MAI0001 - NIHARIKA MAITRA

git Repo Link :  https://github.com/Niharika-20-MAI-01/Winter-2021-Deep-Learning-LabCSE6037-Niharika-20MAI01/blob/main/20MAI0001_DL_single_layer_Perceptron_Prob_1_Asgn_1.ipynb

Implementing Single Layer Perceptron

In [ ]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from pandas import DataFrame
from matplotlib import pyplot as pyplot
from sklearn.linear_model import Perceptron

from sklearn.model_selection import train_test_split

In [ ]:
Input1 = [[1,0,0,1,0,1,1,0,1,1],[0,1,0,0,0,1,0,1,0,0],[1,1,0,1,0,0,1,1,1,1],[0, 	1, 	0, 	1, 	0, 	1, 	0, 	1, 	0,0],
         [1, 	0, 	1, 	0, 	0, 	0, 	1, 	0, 	0,0],[1, 	1, 	1, 	1, 	1, 	1, 	0, 	1, 	1,1],[1, 	1, 	1, 	0, 	1, 	1, 	1, 	1, 	0,1],
         [0, 	1, 	1, 	0, 	1, 	0, 	0, 	0, 	0,1],[1, 	1, 	0, 	1, 	1, 	1, 	1, 	1, 	1,1],[1, 	0, 	0, 	1, 	1, 	0, 	1, 	0, 	1,1]
         ]
#Input2 = [1,0,1,0,0,1,1,0,1,1]
#Input = zip(Input1,Input2)

In [ ]:
data = pd.DataFrame(Input1)

In [ ]:
var1 = ['X'+ str(s) for s in range(1,11)]
data.columns = var1


In [ ]:
print(data.shape)

(10, 10)


In [ ]:
print(data.head())

   X1  X2  X3  X4  X5  X6  X7  X8  X9  X10
0   1   0   0   1   0   1   1   0   1    1
1   0   1   0   0   0   1   0   1   0    0
2   1   1   0   1   0   0   1   1   1    1
3   0   1   0   1   0   1   0   1   0    0
4   1   0   1   0   0   0   1   0   0    0


In [ ]:
print(data.tail())

   X1  X2  X3  X4  X5  X6  X7  X8  X9  X10
5   1   1   1   1   1   1   0   1   1    1
6   1   1   1   0   1   1   1   1   0    1
7   0   1   1   0   1   0   0   0   0    1
8   1   1   0   1   1   1   1   1   1    1
9   1   0   0   1   1   0   1   0   1    1


In [ ]:
print(data)

   X1  X2  X3  X4  X5  X6  X7  X8  X9  X10
0   1   0   0   1   0   1   1   0   1    1
1   0   1   0   0   0   1   0   1   0    0
2   1   1   0   1   0   0   1   1   1    1
3   0   1   0   1   0   1   0   1   0    0
4   1   0   1   0   0   0   1   0   0    0
5   1   1   1   1   1   1   0   1   1    1
6   1   1   1   0   1   1   1   1   0    1
7   0   1   1   0   1   0   0   0   0    1
8   1   1   0   1   1   1   1   1   1    1
9   1   0   0   1   1   0   1   0   1    1


In [ ]:
X = data[['X1','X2','X3','X4','X5','X6','X7','X8','X9']]
Y = data['X10']


In [ ]:
X

X1  X2  X3  X4  X5  X6  X7  X8  X9
0   1   0   0   1   0   1   1   0   1
1   0   1   0   0   0   1   0   1   0
2   1   1   0   1   0   0   1   1   1
3   0   1   0   1   0   1   0   1   0
4   1   0   1   0   0   0   1   0   0
5   1   1   1   1   1   1   0   1   1
6   1   1   1   0   1   1   1   1   0
7   0   1   1   0   1   0   0   0   0
8   1   1   0   1   1   1   1   1   1
9   1   0   0   1   1   0   1   0   1

In [ ]:
Y

0    1
1    0
2    1
3    0
4    0
5    1
6    1
7    1
8    1
9    1
Name: X10, dtype: int64

Train Test split

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)
print(Y_train.shape,Y_test.shape,Y.shape)

(8,) (2,) (10,)


In [ ]:
X_train = X_train.values
X_test = X_test.values

In [ ]:
type(X_train)
type(X_test)

numpy.ndarray

In [ ]:
b=4

from random import randint
i = randint(0,X_train.shape[0])

# Building the logic for our ML classification Model with the training data as input feeding into it 
if(np.sum(X_train[i,:])>b):
    print(1)
else:
    print(0)
    
#Building the logic to check whether Model Prediction of Label is same and accurate to the Target Variable Value for particular Feature Vector(X)    
if(Y_train[i]==1):
    print(1)
else:
    print(0)

1
1


In [ ]:
#Training accuracy
for b in range(X_train.shape[1]+1):
    accurate_rows = 0
    y_pred = 0
    for x,y in zip(X_train, Y_train):
        y_pred = (np.sum(x)>b)
        accurate_rows+= (y == y_pred)
  
    print('For b= ',b ,'on training set, Accurate rows: ', accurate_rows , 'Accuracy= ',accurate_rows/X_train.shape[0])

For b=  0 on training set, Accurate rows:  6 Accuracy=  0.75
For b=  1 on training set, Accurate rows:  6 Accuracy=  0.75
For b=  2 on training set, Accurate rows:  6 Accuracy=  0.75
For b=  3 on training set, Accurate rows:  6 Accuracy=  0.75
For b=  4 on training set, Accurate rows:  7 Accuracy=  0.875
For b=  5 on training set, Accurate rows:  5 Accuracy=  0.625
For b=  6 on training set, Accurate rows:  4 Accuracy=  0.5
For b=  7 on training set, Accurate rows:  3 Accuracy=  0.375
For b=  8 on training set, Accurate rows:  2 Accuracy=  0.25
For b=  9 on training set, Accurate rows:  2 Accuracy=  0.25


In [ ]:
X_test

array([[0, 1, 0, 0, 0, 1, 0, 1, 0],
       [1, 1, 0, 1, 1, 1, 1, 1, 1]])

In [ ]:
Y_test

1    0
8    1
Name: X10, dtype: int64

In [ ]:
#Testing  Accuracy
acc_rows=0
t=X_test.shape[0]
b=4
pred=[]
for x,y in zip(X_test, Y_test):
        y_pred1 = (np.sum(x)>b)
        print(y_pred1)
        acc_rows+= (y == y_pred1)
        if(y_pred1==1):
          pred.append(1)
        else:
          pred.append(0)
print(pred)
print('For b= ',b ,'on testing set, Accurate rows: ', acc_rows , 'Accuracy= ',acc_rows/t)




False
True
[0, 1]
For b=  4 on testing set, Accurate rows:  2 Accuracy=  1.0


In [ ]:
Y_test

1    0
8    1
Name: X10, dtype: int64

In [ ]:
pred

[0, 1]

In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix
print(metrics.confusion_matrix(Y_test,pred))

[[1 0]
 [0 1]]


In [ ]:
from sklearn.metrics import accuracy_score
print(metrics.accuracy_score(Y_test,pred))

1.0


In [ ]:
print(classification_report(Y_test,pred))



              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         1

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2



In [ ]:
#Training  Accuracy=  0.875
#Testing Accuracy=  1.0 

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3,stratify=Y,random_state=3)
print(Y_train.shape,Y_test.shape,Y.shape)

(7,) (3,) (10,)


In [ ]:
X_train = X_train.values
X_test = X_test.values

In [ ]:
#Training accuracy
for b in range(X_train.shape[1]+1):
    accurate_rows = 0
    y_pred = 0
    for x,y in zip(X_train, Y_train):
        y_pred = (np.sum(x)>b)
        accurate_rows+= (y == y_pred)
  
    print('For b= ',b ,'on training set, Accurate rows: ', accurate_rows , 'Accuracy= ',accurate_rows/X_train.shape[0])

For b=  0 on training set, Accurate rows:  5 Accuracy=  0.7142857142857143
For b=  1 on training set, Accurate rows:  5 Accuracy=  0.7142857142857143
For b=  2 on training set, Accurate rows:  5 Accuracy=  0.7142857142857143
For b=  3 on training set, Accurate rows:  5 Accuracy=  0.7142857142857143
For b=  4 on training set, Accurate rows:  6 Accuracy=  0.8571428571428571
For b=  5 on training set, Accurate rows:  4 Accuracy=  0.5714285714285714
For b=  6 on training set, Accurate rows:  4 Accuracy=  0.5714285714285714
For b=  7 on training set, Accurate rows:  4 Accuracy=  0.5714285714285714
For b=  8 on training set, Accurate rows:  2 Accuracy=  0.2857142857142857
For b=  9 on training set, Accurate rows:  2 Accuracy=  0.2857142857142857


In [ ]:
#Testing  Accuracy
acc_rows=0
t=X_test.shape[0]
b=4
pred=[]
for x,y in zip(X_test, Y_test):
        y_pred1 = (np.sum(x)>b)
        print(y_pred1)
        acc_rows+= (y == y_pred1)
        if(y_pred1==1):
          pred.append(1)
        else:
          pred.append(0)
print(pred)
print('For b= ',b ,'on testing set, Accurate rows: ', acc_rows , 'Accuracy= ',acc_rows/t)




False
True
True
[0, 1, 1]
For b=  4 on testing set, Accurate rows:  3 Accuracy=  1.0


In [ ]:
print(metrics.confusion_matrix(Y_test,pred))

[[1 0]
 [0 2]]


In [ ]:
print(metrics.accuracy_score(Y_test,pred))

1.0


In [ ]:
print(classification_report(Y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         2

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3



In [ ]:
#Training Accuracy=  0.8571428571428571
#Testing Accuracy=  1.0

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.4,stratify=Y,random_state=4)
print(Y_train.shape,Y_test.shape,Y.shape)

(6,) (4,) (10,)


In [ ]:
X_train = X_train.values
X_test = X_test.values

In [ ]:
#Training accuracy
for b in range(X_train.shape[1]+1):
    accurate_rows = 0
    y_pred = 0
    for x,y in zip(X_train, Y_train):
        y_pred = (np.sum(x)>b)
        accurate_rows+= (y == y_pred)
  
    print('For b= ',b ,'on training set, Accurate rows: ', accurate_rows , 'Accuracy= ',accurate_rows/X_train.shape[0])

For b=  0 on training set, Accurate rows:  4 Accuracy=  0.6666666666666666
For b=  1 on training set, Accurate rows:  4 Accuracy=  0.6666666666666666
For b=  2 on training set, Accurate rows:  4 Accuracy=  0.6666666666666666
For b=  3 on training set, Accurate rows:  4 Accuracy=  0.6666666666666666
For b=  4 on training set, Accurate rows:  5 Accuracy=  0.8333333333333334
For b=  5 on training set, Accurate rows:  4 Accuracy=  0.6666666666666666
For b=  6 on training set, Accurate rows:  4 Accuracy=  0.6666666666666666
For b=  7 on training set, Accurate rows:  3 Accuracy=  0.5
For b=  8 on training set, Accurate rows:  2 Accuracy=  0.3333333333333333
For b=  9 on training set, Accurate rows:  2 Accuracy=  0.3333333333333333


In [ ]:
#Testing  Accuracy
acc_rows=0
t=X_test.shape[0]
b=4
pred=[]
for x,y in zip(X_test, Y_test):
        y_pred1 = (np.sum(x)>b)
        print(y_pred1)
        acc_rows+= (y == y_pred1)
        if(y_pred1==1):
          pred.append(1)
        else:
          pred.append(0)
print(pred)
print('For b= ',b ,'on testing set, Accurate rows: ', acc_rows , 'Accuracy= ',acc_rows/t)




True
False
True
True
[1, 0, 1, 1]
For b=  4 on testing set, Accurate rows:  4 Accuracy=  1.0


In [ ]:
print(metrics.confusion_matrix(Y_test,pred))

[[1 0]
 [0 3]]


In [ ]:
print(metrics.accuracy_score(Y_test,pred))

1.0


In [ ]:
print(classification_report(Y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         3

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



In [ ]:
#Training  Accuracy=  0.8333333333333334
#Testing Accuracy=  1.0

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.5,stratify=Y,random_state=5)
print(Y_train.shape,Y_test.shape,Y.shape)

(5,) (5,) (10,)


In [ ]:
X_train = X_train.values
X_test = X_test.values

In [ ]:
#Training accuracy
for b in range(X_train.shape[1]+1):
    accurate_rows = 0
    y_pred = 0
    for x,y in zip(X_train, Y_train):
        y_pred = (np.sum(x)>b)
        accurate_rows+= (y == y_pred)
  
    print('For b= ',b ,'on training set, Accurate rows: ', accurate_rows , 'Accuracy= ',accurate_rows/X_train.shape[0])

For b=  0 on training set, Accurate rows:  3 Accuracy=  0.6
For b=  1 on training set, Accurate rows:  3 Accuracy=  0.6
For b=  2 on training set, Accurate rows:  3 Accuracy=  0.6
For b=  3 on training set, Accurate rows:  3 Accuracy=  0.6
For b=  4 on training set, Accurate rows:  4 Accuracy=  0.8
For b=  5 on training set, Accurate rows:  4 Accuracy=  0.8
For b=  6 on training set, Accurate rows:  4 Accuracy=  0.8
For b=  7 on training set, Accurate rows:  3 Accuracy=  0.6
For b=  8 on training set, Accurate rows:  2 Accuracy=  0.4
For b=  9 on training set, Accurate rows:  2 Accuracy=  0.4


In [ ]:
#Testing  Accuracy
acc_rows=0
t=X_test.shape[0]
b=4
pred=[]
for x,y in zip(X_test, Y_test):
        y_pred1 = (np.sum(x)>b)
        print(y_pred1)
        acc_rows+= (y == y_pred1)
        if(y_pred1==1):
          pred.append(1)
        else:
          pred.append(0)
print(pred)
print('For b= ',b ,'on testing set, Accurate rows: ', acc_rows , 'Accuracy= ',acc_rows/t)




False
True
True
True
True
[0, 1, 1, 1, 1]
For b=  4 on testing set, Accurate rows:  5 Accuracy=  1.0


In [ ]:
print(metrics.confusion_matrix(Y_test,pred))

[[1 0]
 [0 4]]


In [ ]:
print(metrics.accuracy_score(Y_test,pred))

1.0


In [ ]:
print(classification_report(Y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         4

    accuracy                           1.00         5
   macro avg       1.00      1.00      1.00         5
weighted avg       1.00      1.00      1.00         5



In [ ]:
#Training  Accuracy=  0.8
#Testing Accuracy=  1.0