<a href="https://colab.research.google.com/github/Niharika-20-MAI-01/Winter-2021-Deep-Learning-LabCSE6037-Niharika-20MAI01/blob/main/20MAI0001_DL_Multi_layer_Perceptron_Prob_2_Asgn_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DL-Lab-CSE6037_Lab-Assignment-1_Problem-2_Multi_Layer_Perceptron

Submitted By: 20MAI0001 - NIHARIKA MAITRA

git Repo Link :   https://github.com/Niharika-20-MAI-01/Winter-2021-Deep-Learning-LabCSE6037-Niharika-20MAI01/blob/main/20MAI0001_DL_Multi_layer_Perceptron_Prob_2_Asgn_1.ipynb

In [ ]:
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler  
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import LabelEncoder 
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from pandas import DataFrame
from matplotlib import pyplot as pyplot
from sklearn.linear_model import Perceptron


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving iris.data to iris (2).data


In [ ]:
col_names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [ ]:
data = pd.read_csv('iris.data', names=col_names)

In [ ]:
print(data.shape)

(150, 5)


In [ ]:
data.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
data.tail()

sepal-length  sepal-width  petal-length  petal-width           Class
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [ ]:
data

sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
X = data[['sepal-length', 'sepal-width', 'petal-length', 'petal-width']]
Y = data['Class']
#y = data.select_dtypes(include=[object])

In [ ]:
X

sepal-length  sepal-width  petal-length  petal-width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [ ]:
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Class, Length: 150, dtype: object

In [ ]:
np.unique(Y)

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
#To identify how many records fall under each Class Type
print(data['Class'].value_counts())

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        50
Name: Class, dtype: int64


In [ ]:
# To transform categorial into numerical values
numb= LabelEncoder()
Y = numb.fit_transform(Y.astype('str'))


In [ ]:
Y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

Train_Test_Split

In [ ]:

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)
print(Y_train.shape,Y_test.shape,Y.shape)

(120,) (30,) (150,)


In [ ]:
type(Y_train)

numpy.ndarray

In [ ]:
#Feature Scaling
sc = StandardScaler()  
sc.fit(X_train)
X_train = sc.transform(X_train)  
X_test = sc.transform(X_test)

In [ ]:
#Implementing  Multilayer Perceptron
mlp1 = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
mlp1.fit(X_train, Y_train.ravel())

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [ ]:
train_pred = mlp1.predict(X_train)
print(train_pred)


[1 2 2 2 0 1 1 2 1 1 2 1 1 1 2 1 2 2 0 2 2 2 1 0 2 2 0 1 2 0 2 2 2 0 2 1 1
 2 0 2 1 1 1 0 0 2 2 2 2 0 2 0 0 0 2 0 0 0 1 0 2 0 2 1 0 0 1 1 0 1 1 0 0 1
 0 2 0 1 0 1 1 1 0 1 2 1 2 2 0 2 0 0 1 1 1 2 2 0 0 0 1 1 2 0 0 1 0 0 1 2 2
 2 0 1 1 1 1 0 0 2]


In [ ]:
print('Training_Accuracy =  '+str(metrics.accuracy_score(Y_train,train_pred)))

Training_Accuracy =  0.9833333333333333


In [ ]:
test_pred = mlp1.predict(X_test)
print(test_pred)

[0 2 2 0 1 2 2 2 0 0 1 1 1 2 0 2 1 0 2 0 1 1 0 1 1 2 2 0 1 0]


In [ ]:
print('Testing_Accuracy =  '+str(metrics.accuracy_score(Y_test,test_pred)))

Testing_Accuracy =  1.0


In [ ]:
print(metrics.confusion_matrix(Y_test,test_pred))

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]


In [ ]:
print(classification_report(Y_test,test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
#Training_Accuracy =  0.9833333333333333
#Testing_Accuracy =  1.0

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3,stratify=Y,random_state=3)
print(Y_train.shape,Y_test.shape,Y.shape)

(105,) (45,) (150,)


In [ ]:
#Feature Scaling
sc = StandardScaler()  
sc.fit(X_train)
X_train = sc.transform(X_train)  
X_test = sc.transform(X_test)

In [ ]:
#Implementing  Multilayer Perceptron
mlp1 = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
mlp1.fit(X_train, Y_train.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [ ]:
train_pred = mlp1.predict(X_train)
print(train_pred)
print('\n')
print('Training_Accuracy =  '+str(metrics.accuracy_score(Y_train,train_pred)))

[0 0 0 1 1 1 0 2 0 0 1 0 1 2 0 1 2 2 2 0 0 1 2 0 2 0 0 2 2 2 1 2 0 0 1 2 1
 2 2 2 1 2 1 1 2 1 1 2 1 2 0 1 2 0 0 0 0 1 2 2 1 0 0 0 1 1 2 0 0 0 1 1 1 1
 2 2 1 1 1 0 2 2 2 0 2 1 2 0 2 2 2 1 1 2 1 0 0 0 1 2 0 0 0 2 1]


Training_Accuracy =  0.9904761904761905


In [ ]:
test_pred = mlp1.predict(X_test)
print(test_pred)
print('\n')
print('Testing_Accuracy =  '+str(metrics.accuracy_score(Y_test,test_pred)))

[0 2 0 1 1 2 0 1 2 1 2 0 1 1 1 2 2 2 1 0 2 2 2 0 0 1 0 0 2 2 2 0 2 1 2 0 0
 0 0 1 1 0 1 2 1]


Testing_Accuracy =  0.9333333333333333


In [ ]:
print(metrics.confusion_matrix(Y_test,test_pred))

[[15  0  0]
 [ 0 13  2]
 [ 0  1 14]]


In [ ]:
print(classification_report(Y_test,test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.93      0.87      0.90        15
           2       0.88      0.93      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45



In [ ]:
#Training_Accuracy =  0.9904761904761905
#Testing_Accuracy =  0.9333333333333333

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.4,stratify=Y,random_state=4)
print(Y_train.shape,Y_test.shape,Y.shape)

(90,) (60,) (150,)


In [ ]:
#Feature Scaling
sc = StandardScaler()  
sc.fit(X_train)
X_train = sc.transform(X_train)  
X_test = sc.transform(X_test)

In [ ]:
#Implementing  Multilayer Perceptron
mlp1 = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
mlp1.fit(X_train, Y_train.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [ ]:
train_pred = mlp1.predict(X_train)
print(train_pred)
print('\n')
print('Training_Accuracy =  '+str(metrics.accuracy_score(Y_train,train_pred)))

[0 2 1 0 1 1 1 2 2 1 2 2 1 2 0 1 1 2 2 1 0 2 1 2 1 2 1 0 0 0 0 1 2 2 2 1 2
 0 0 1 0 2 0 0 0 1 1 1 0 1 1 0 2 2 2 1 2 1 2 2 0 1 0 1 2 0 0 0 0 1 2 0 2 2
 1 1 0 2 2 1 0 2 0 0 2 0 0 2 1 0]


Training_Accuracy =  0.9888888888888889


In [ ]:
test_pred = mlp1.predict(X_test)
print(test_pred)
print('\n')
print('Testing_Accuracy =  '+str(metrics.accuracy_score(Y_test,test_pred)))

[2 2 0 1 0 0 1 2 0 2 1 0 0 0 1 2 1 2 1 2 2 2 1 2 2 1 1 0 0 2 0 0 1 0 0 1 1
 2 2 2 1 1 0 0 2 0 0 2 1 2 1 0 1 0 2 1 2 0 2 2]


Testing_Accuracy =  0.9333333333333333


In [ ]:
print(metrics.confusion_matrix(Y_test,test_pred))

[[20  0  0]
 [ 0 17  3]
 [ 0  1 19]]


In [ ]:
print(classification_report(Y_test,test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        20
           1       0.94      0.85      0.89        20
           2       0.86      0.95      0.90        20

    accuracy                           0.93        60
   macro avg       0.94      0.93      0.93        60
weighted avg       0.94      0.93      0.93        60



In [ ]:
#Training_Accuracy =  0.9888888888888889
#Testing_Accuracy =  0.9333333333333333

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.5,stratify=Y,random_state=5)
print(Y_train.shape,Y_test.shape,Y.shape)

(75,) (75,) (150,)


In [ ]:
#Feature Scaling
sc = StandardScaler()  
sc.fit(X_train)
X_train = sc.transform(X_train)  
X_test = sc.transform(X_test)

In [ ]:
#Implementing  Multilayer Perceptron
mlp1 = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)  
mlp1.fit(X_train, Y_train.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=1000,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [ ]:
train_pred = mlp1.predict(X_train)
print(train_pred)
print('\n')
print('Training_Accuracy =  '+str(metrics.accuracy_score(Y_train,train_pred)))

[0 2 2 2 1 0 2 1 0 0 0 1 2 1 1 1 2 2 0 0 2 0 2 1 1 1 2 1 1 0 2 1 2 1 1 0 0
 1 1 1 2 0 0 1 2 1 2 2 2 0 0 2 0 0 0 2 2 2 0 1 0 1 1 2 0 0 1 2 1 0 1 2 0 0
 2]


Training_Accuracy =  1.0


In [ ]:
test_pred = mlp1.predict(X_test)
print(test_pred)
print('\n')
print('Testing_Accuracy =  '+str(metrics.accuracy_score(Y_test,test_pred)))

[2 2 0 1 1 0 0 2 2 0 2 2 1 0 1 2 1 2 1 0 0 0 1 2 1 0 1 2 2 0 0 2 1 0 0 0 1
 1 2 1 1 0 2 2 2 0 2 2 1 1 0 1 2 0 0 1 0 1 1 2 0 2 2 0 0 2 2 1 1 1 0 1 1 2
 0]


Testing_Accuracy =  0.9466666666666667


In [ ]:
print(metrics.confusion_matrix(Y_test,test_pred))

[[25  0  0]
 [ 0 23  2]
 [ 0  2 23]]


In [ ]:
print(classification_report(Y_test,test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.92      0.92        25
           2       0.92      0.92      0.92        25

    accuracy                           0.95        75
   macro avg       0.95      0.95      0.95        75
weighted avg       0.95      0.95      0.95        75



In [ ]:
#Training_Accuracy =  1.0
#Testing_Accuracy =  0.9466666666666667