<a href="https://colab.research.google.com/github/Niharika-20-MAI-01/Winter-2021-Deep-Learning-LabCSE6037-Niharika-20MAI01/blob/main/DL_lab_Asgn_1_prob_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as pyplot
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split

In [34]:
from google.colab import files
uploaded = files.upload()

In [35]:
data = pd.read_csv('DL-labAS-1.csv', header = None)

In [36]:
varname1 = ['X'+ str(s) for s in range(1,11)]
data.columns = varname1

In [37]:
import io
df = pd.DataFrame(data)

In [43]:
data

X1  X2  X3  X4  X5  X6  X7  X8  X9  X10
0   1   0   0   1   0   1   1   0   1    1
1   0   1   0   0   0   1   0   1   0    0
2   1   1   0   1   0   0   1   1   1    1
3   0   1   0   1   0   1   0   1   0    0
4   1   0   1   0   0   0   1   0   0    0
5   1   1   1   1   1   1   0   1   1    1
6   1   1   1   0   1   1   1   1   0    1
7   0   1   1   0   1   0   0   0   0    0
8   1   1   0   1   1   1   1   1   1    1
9   1   0   0   1   1   0   1   0   1    1

In [39]:
data.head()

X1  X2  X3  X4  X5  X6  X7  X8  X9  X10
0   1   0   0   1   0   1   1   0   1    1
1   0   1   0   0   0   1   0   1   0    0
2   1   1   0   1   0   0   1   1   1    1
3   0   1   0   1   0   1   0   1   0    0
4   1   0   1   0   0   0   1   0   0    0

In [40]:
data.tail()

X1  X2  X3  X4  X5  X6  X7  X8  X9  X10
5   1   1   1   1   1   1   0   1   1    1
6   1   1   1   0   1   1   1   1   0    1
7   0   1   1   0   1   0   0   0   0    0
8   1   1   0   1   1   1   1   1   1    1
9   1   0   0   1   1   0   1   0   1    1

In [44]:
data.shape

(10, 10)

In [45]:
X_data = df[['X1','X2','X3','X4','X5','X6','X7','X8','X9']]
Y_data = df['X10']

In [46]:
X_data 

X1  X2  X3  X4  X5  X6  X7  X8  X9
0   1   0   0   1   0   1   1   0   1
1   0   1   0   0   0   1   0   1   0
2   1   1   0   1   0   0   1   1   1
3   0   1   0   1   0   1   0   1   0
4   1   0   1   0   0   0   1   0   0
5   1   1   1   1   1   1   0   1   1
6   1   1   1   0   1   1   1   1   0
7   0   1   1   0   1   0   0   0   0
8   1   1   0   1   1   1   1   1   1
9   1   0   0   1   1   0   1   0   1

In [47]:
Y_data

0    1
1    0
2    1
3    0
4    0
5    1
6    1
7    0
8    1
9    1
Name: X10, dtype: int64

In [48]:
X_data.shape, Y_data.shape

((10, 9), (10,))

In [70]:
X_data_train, X_data_test, Y_data_train, Y_data_test = train_test_split(X_data,Y_data,test_size=0.1,random_state=0)

In [71]:
X_data_train.shape, Y_data_train.shape

((9, 9), (9,))

In [72]:
per1 = Perceptron(random_state=0)

In [73]:
per1.fit(X_data_train, Y_data_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [75]:
pred1 = per1.predict(X_data_test)
pred1

array([0])

In [76]:
per1.score(X_data_test, Y_data_test)

0.0

In [62]:
X_data_train, X_data_test, Y_data_train, Y_data_test = train_test_split(X_data,Y_data,test_size=0.2,random_state=0)

In [64]:
X_data_train.shape, Y_data_train.shape

((8, 9), (8,))

In [67]:
per2 = Perceptron(random_state=0)
per2.fit(X_data_train, Y_data_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [68]:
pred2 = per2.predict(X_data_test)
pred2

array([1, 1])

In [69]:
per2.score(X_data_test, Y_data_test)

1.0

In [77]:
X_data_train, X_data_test, Y_data_train, Y_data_test = train_test_split(X_data,Y_data,test_size=0.3,random_state=0)

In [79]:
X_data_train.shape, Y_data_train.shape

((7, 9), (7,))

In [80]:
per3 = Perceptron(random_state=0)
per3.fit(X_data_train, Y_data_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [81]:
pred3 = per3.predict(X_data_test)
pred3

array([1, 1, 1])

In [82]:
per3.score(X_data_test, Y_data_test)

0.6666666666666666

In [98]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_data_test, pred3)

ValueError: ignored

In [83]:
X_data_train, X_data_test, Y_data_train, Y_data_test = train_test_split(X_data,Y_data,test_size=0.4,random_state=0)

In [84]:
X_data_train.shape, Y_data_train.shape

((6, 9), (6,))

In [85]:
per4 = Perceptron(random_state=0)
per4.fit(X_data_train, Y_data_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [87]:
pred4 = per4.predict(X_data_test)
pred4

array([1, 1, 1, 1])

In [88]:
per3.score(X_data_test, Y_data_test)

0.75

In [89]:
X_data_train, X_data_test, Y_data_train, Y_data_test = train_test_split(X_data,Y_data,test_size=0.5,random_state=0)

In [90]:
X_data_train.shape, Y_data_train.shape

((5, 9), (5,))

In [91]:
per5 = Perceptron(random_state=0)
per5.fit(X_data_train, Y_data_train)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [92]:
pred5 = per5.predict(X_data_test)
pred5

array([1, 1, 1, 1, 0])

In [93]:
per5.score(X_data_test, Y_data_test)

0.8